/*
  IMPORTANT: This file is automatically generated by Netlify.
  Any changes may be overwritten. Use netlify.toml for custom configuration.
*/
const { createRequire } = require('node:module');
const { join, dirname, relative } = require('node:path');
const { readFile, stat, mkdir, copyFile, rm } = require('node:fs/promises');
const { existsSync, mkdirSync, copyFileSync, unlinkSync, rmdirSync } = require('node:fs');
require('dotenv').config();

const require = createRequire(import.meta.url);
const rootDir = process.cwd();
const buildDir = join(rootDir, 'dist', 'client');

async function copyPublic(context) {
  const publicDir = join(rootDir, 'public');
  try {
    const publicStats = await stat(publicDir);
    if (publicStats.isDirectory()) {
      await copyFolder(publicDir, join(buildDir, 'public'));
    }
  } catch {
    // No public directory
  }
}

async function copyFolder(source, target) {
  try {
    await mkdir(target, { recursive: true });
    const items = await readdir(source);
    for (const item of items) {
      const sourcePath = join(source, item);
      const targetPath = join(target, item);
      const stats = await stat(sourcePath);
      if (stats.isDirectory()) {
        await copyFolder(sourcePath, targetPath);
      } else {
        await copyFile(sourcePath, targetPath);
      }
    }
  } catch (err) {
    console.error('Error copying folder:', err);
  }
}

async function main() {
  try {
    await copyPublic();
    console.log('Netlify build completed successfully');
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

main();
